### ISSUE TITLE
How to add match results?

### ISSUE THREAD

**Issue by sfabriece** [funkindy/ranker#47]
Hi @funkindy, I'm playing around with this awesome project but I can't figure out how registering match results should be done. Specifically:

 - Winner rating
 - Looser rating
 - Delta

Are they supposed to be computed automatically?

**Comment by funkindy** [comment]
Hi! Yes, you can add players and match results via admin panel. All ratings and deltas are calculated automatically with ELO-like formulas

**Comment by sfabriece** [comment]
Thanks for the quick response @funkindy. It seems like the admin panel wants me to add the winner, looser and delta manually. When I try to save I get validation errors.

![image](https://user-images.githubusercontent.com/3108592/187896154-d6883dd4-f907-4765-a13a-c41c4ce34c29.png)

**Comment by sfabriece** [comment]
Also another question: do we register the score of a game or match? meaning 11 - 4 or 1 -0.

**Comment by funkindy** [comment]
To be honest i didn't touch the project for years :) but ill take a look shortly

**Comment by sfabriece** [comment]
Understandable. I had to make some changes locally to make it work. I'll create a PR with my changes just in case it'll help you to get up and running now.

**Comment by funkindy** [comment]
Yes, sure!

**Comment by funkindy** [comment]
@sfabriece i've made a quick fix for match saving. Now all is calculated automatically on match save. About the score - my intention (as far as i remember)  was to keep the entire match score in sets (4-3, 3-1 or even 1-0 for quick games), not the points in a set.

**Comment by sfabriece** [comment]
Awesome @funkindy . I'll check it out asap.

**Comment by sfabriece** [comment]
@funkindy  It's looking good so far. The only problem that is remaining is that when I do the following I get a 500 error on the leaderboard api:

 - go to admin panel
 - got to players and remove all the demom players
 - Add 2 new players
 - Add 2 new match results involving the players
 - Go to the public page and look at the network call

**Comment by funkindy** [comment]
> @funkindy It's looking good so far. The only problem that is remaining is that when I do the following I get a 500 error on the leaderboard api:
> 
> * go to admin panel
> * got to players and remove all the demom players
> * Add 2 new players
> * Add 2 new match results involving the players
> * Go to the public page and look at the network call

Just pushed a fix for low games case

**Comment by sfabriece** [comment]
@funkindy I seem to be getting the following errors with a brand new DB when loading the leaderboard after pulling in your changes:

```
[01/Sep/2022 16:48:37] "GET /api/v1/players/leaderboard HTTP/1.1" 500 117886
[01/Sep/2022 16:49:03] "GET / HTTP/1.1" 200 810
Internal Server Error: /api/v1/players/leaderboard
Traceback (most recent call last):
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/ranker/core/views.py", line 34, in get
    maxes = data.get_maxes()
  File "/Users/fabriece/github/masterblaster/ranker/ranker/core/services/data.py", line 192, in get_maxes
    'name': Player.objects.get(pk=idx).full_name,
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/fabriece/github/masterblaster/ranker/localenv/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
ranker.core.models.Player.DoesNotExist: Player matching query does not exist.
```

**Comment by funkindy** [comment]
I think that i just dont handle the empty case) will look at it tommorow

**Comment by funkindy** [comment]
@sfabriece just tried on fresh db. Only executed `migrate` and `createcachetable` after.
Leaderboard cards are empty but no api errors. Response:
![image](https://user-images.githubusercontent.com/17568549/187951268-87bb5b2a-d134-4a69-a3c0-1734897120dc.png)

what steps to take to reproduce your issue?

**Comment by sfabriece** [comment]
Did you add 2 players and 2 match results? @funkindy

**Comment by funkindy** [comment]
@sfabriece yeah i see. Fixed now

**Comment by sfabriece** [comment]
Perfect, it works. Thanks for the speedy feedback. @funkindy
